Automatic Stats Action
Ryujinx/Ryujinx-Games-List pull request #4682
Opened 2023-07-12 18:36 UTC by IsaacMarovitz

Used for: https://github.com/Ryujinx/Ryujinx-Website/pull/27

2023-07-24 22:51 UTC, TSRBerry requested changes
I know I'm being picky here, but I hope these change requests are fine for you.

2023-07-24 22:51 UTC, TSRBerry commented on .github/stats.py
> +import requests, json
Could you use [github-script](https://github.com/actions/github-script) or gh-cli instead of this?
So we have everything included in the workflow?

2023-07-24 22:51 UTC, TSRBerry commented on .github/stats.py
> +with open("issue-data.json", "w") as outfile:
How about `compat-stats.json` instead?

2023-07-24 22:51 UTC, TSRBerry commented on .github/workflows/label-stats.yml
> +name: Generate label stats
Check the workflows on the main repo for hints on how to format this file.

2023-07-24 22:51 UTC, TSRBerry commented on .github/workflows/label-stats.yml
> +          commit_message: Update compatability statistics
We don't need a third-party action for that. Pushing a commit is about 3 commands on GitHub Actions.

2023-07-24 22:51 UTC, TSRBerry commented on issue-data.json
> +{
Let the workflow generate the file instead and remove it from the PR.
This way we get another commit with the right timestamp attached, which could be useful for some other stats we could provide in the future.

2023-07-25 13:38 UTC, TSRBerry commented on .github/workflows/label-stats.yml
> +            const string = JSON.stringify(formattedData, null, 2).replaceAll('\"', '\\"');
Could you explain this line? I don't understand why it's needed.

2023-07-26 04:44 UTC, IsaacMarovitz commented on .github/workflows/label-stats.yml
> +            const string = JSON.stringify(formattedData, null, 2).replaceAll('\"', '\\"');
I need it as a string so I can echo it into the file. I can’t just return the TypeScript JSON afaik

2023-07-26 12:19 UTC, TSRBerry commented on .github/workflows/label-stats.yml
> +            const string = JSON.stringify(formattedData, null, 2).replaceAll('\"', '\\"');
What about the replace part?

2023-07-28 17:16 UTC, TSRBerry requested changes
I learned a bit more about how we are supposed to do this and now have a few more change requests.

2023-07-28 17:16 UTC, TSRBerry commented on .github/workflows/label-stats.yml
> +        run: echo "${{steps.stats.outputs.result}}" > compat-stats.json
```suggestion
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          cat << $EOF > compat-stats.json
          ${{steps.stats.outputs.result}}
          $EOF
```

See: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings

2023-07-28 17:16 UTC, TSRBerry commented on .github/workflows/label-stats.yml
> +          git push
```suggestion
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Update compat-stats.json"
          git push

```

Use the correct name and email for github-actions and don't forget the trailing newline.

2023-07-28 17:16 UTC, TSRBerry commented on .github/workflows/label-stats.yml
> +        uses: actions/checkout@v3
```suggestion
        uses: actions/checkout@v3
        with:
          ref: master
```

Make sure we are checking out the master branch here.

2023-07-28 22:09 UTC, TSRBerry approved these changes
Lgtm otherwise, thanks for being patient with me!

2023-07-28 22:09 UTC, TSRBerry commented on compat-stats.json
Could you remove this file again? It should not be merged with this PR.

2023-07-28 23:47 UTC, IsaacMarovitz commented
> Lgtm otherwise, thanks for being patient with me!

Due to the cron on the job that file gets added automatically, idk when the final review will come thru might be more than a day.

2023-09-20 15:33 UTC, marysaka approved these changes

2023-09-20 15:59 UTC, merged